"""empty message

Revision ID: cf84aa5d342d
Revises: c161b4565402
Create Date: 2022-03-03 07:48:13.577876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf84aa5d342d'
down_revision = 'c161b4565402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
